books/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('<int:book_id>/', views.details_books, name='details_books'),
    path('<int:book_id>/edit/', views.edit_books, name='edit_books'),
    path('enter_new_book', views.enter_new_book, name="enter_new_book"),
    path('ajax/load-emails', views.load_emails, name='ajax_load_emails'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cherry_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from books.views import index
# from user_login.views import signup

urlpatterns = [
	path('jet/', include('jet.urls', 'jet')),
	path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
	path('admin/', admin.site.urls),
	path('', index, name='index'),
	path('dashboard/', include('books.urls')),
	# path('accounts/', include('user_login.urls')),
	path('accounts/', include('allauth.urls')),
	path('invitations/', include('invitations.urls', namespace='invitations')),
	# path('invitations/accept-invite/accounts/signup/', signup, name='signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
# from django.forms import ModelForm
from django import forms
from django_select2.forms import Select2MultipleWidget


class Author(models.Model):
	name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)

	def __str__(self):
		return (f"{self.name} {self.last_name}")


class Book(models.Model):
	title = models.CharField(max_length=200)
	subtitle = models.CharField(max_length=200)
	description = models.TextField()
	comparible = models.URLField(max_length=200)
	co_author_name = models.ManyToManyField(Author, related_name='co_author')
	# co_author_email = models.CharField(max_length=100)
	co_author_email = models.ManyToManyField(Author, related_name='co_author_email')
	co_author_instructions = models.TextField()
	# author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='author')
	author = models.ManyToManyField(Author, related_name='author')
	cover = models.ImageField(upload_to='cover_image/', blank=False)

	def __str__(self):
		return f"{self.title}"


class BookForm(forms.ModelForm):
	author = forms.ModelMultipleChoiceField(widget=Select2MultipleWidget, queryset=Author.objects.all())
	co_author_name = forms.ModelMultipleChoiceField(widget=Select2MultipleWidget, queryset=Author.objects.all())
	# co_author_name = forms.ModelChoiceField(queryset=Author.objects.all())
	co_author_email = forms.ModelMultipleChoiceField(widget=Select2MultipleWidget, queryset=Author.objects.all())

	class Meta:
		model = Book
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['co_author_email'].queryset = Author.objects.none()

		# SKONTAJ
		# if('authorId[]' in self.data):
		# 	try:
		# 		country_id = int(self.data.get('authorId[]'))
		# 		self.fields['co_author_email'].queryset = Author.objects.filter(country_id=country_id).order_by('name')
		# 	except (ValueError, TypeError):
		# 		pass  # invalid input from the client; ignore and fallback to empty City queryset
		# elif(self.instance.pk):
		# 	self.fields['co_author_email'].queryset = self.instance.authorId.city_set.order_by('name')

books/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from .models import Author, Book, BookForm
from django.urls import reverse


def index(request):

	return render(request, 'books/index.html', {})


def dashboard(request):
	books = Book.objects.all()
	context = {'books': books}

	return render(request, 'books/dashboard.html', context)


def details_books(request, book_id):
	try:
		book = Book.objects.get(pk=book_id)
		context = {'book': book}
		return render(request, 'books/details_books.html', context)
	except:
		raise Http404("Ne postoji ta knjiga!")


def enter_new_book(request):
	if (request.method == 'POST'):
		form = BookForm(request.POST, request.FILES)
		if (form.is_valid()):
			form.save()
			if ('save_and_add_another' in request.POST):
				return redirect('dashboard:enter_new_book')
			else:
				return redirect('dashboard:dashboard')
	else:
		form = BookForm()

	context = {'form': form}

	return render(request, 'books/enter_new_book.html', context)


def edit_books(request, book_id):
	book = Book.objects.get(pk=book_id)

	if (request.method == 'POST'):
		form = BookForm(request.POST, request.FILES, instance=book)
		if(form.is_valid()):
			form.save()
			return redirect(reverse('dashboard:details_books', args=[book_id]))
	else:
		form = BookForm(instance=book)

	context = {'book': book, 'form': form}

	return render(request, 'books/edit_books.html', context)


# getting AJAX's data and using it to query our DB
def load_emails(request):
	author_id = request.GET.getlist('authorId[]')
	# print(author_id)
	mails = Author.objects.filter(pk__in=author_id)

	return render(request, 'books/displaying_emails_using_ajax.html', {'mails': mails})

books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		Book App - {% block title %} {% endblock %}
	</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}" />
	{% block other_css %} {% endblock %}
</head>
<body>

</div>
<nav class="main-menu">
	<div>
		<a class="logo" href="http://startific.com"></a> 
	</div> 

	<div class="settings"></div>
	<div class="scrollbar" id="style-1">
	<ul>
		<li>                                   
			<a href="#">
				<i class="fa fa-home fa-lg"></i>
				<span class="nav-text">Home</span>
			</a>
		</li>  

		<li> 
			<a href="#">
				<i class="fa fa-envelope-o fa-lg"></i>
				<span class="nav-text">Contact</span>					
			</a>                          
		</li> 

		<li> 
			<a href="#">
				<i class="fa fa-user fa-lg"></i>						
				<span class="nav-text">Login</span>
			</a>                                
			
		</li>  
	
		<!--	
		</li>
		<li class="darkerlishadow">
			<a href="http://startific.com">
				<i class="fa fa-clock-o fa-lg"></i>
				<span class="nav-text">News</span>
			</a>
		</li>

		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-desktop fa-lg"></i>					
				<span class="nav-text">Technology</span>
			</a>
		</li>
			  
		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-plane fa-lg"></i>
				<span class="nav-text">Travel</span>
			</a>
		</li>
				
		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-shopping-cart"></i>
				<span class="nav-text">Shopping</span>
			</a>
		</li>
			  
		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-microphone fa-lg"></i>
				<span class="nav-text">Film & Music</span>
			</a>
		</li>

		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-flask fa-lg"></i>
				<span class="nav-text">Web Tools</span>
			</a>
		</li>
			  
		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-picture-o fa-lg"></i>
				<span class="nav-text">Art & Design</span>
			</a>
		</li>

		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-align-left fa-lg"></i>
				<span class="nav-text">Magazines</span>
			</a>
		</li>
			  
		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-gamepad fa-lg"></i>
				<span class="nav-text">Games</span>
			</a>
		</li>
			  
		<li class="darkerli">
			<a href="http://startific.com">
				<i class="fa fa-glass fa-lg"></i>
				<span class="nav-text">Life & Style</span>
			</a>
		</li>
				  
		<li class="darkerlishadowdown">
			<a href="http://startific.com">
				<i class="fa fa-rocket fa-lg"></i>
				<span class="nav-text">Fun</span>
			</a>
		</li>
	</ul>

	<li>                                   
		<a href="http://startific.com">
			<i class="fa fa-question-circle fa-lg"></i>
			<span class="nav-text">Help</span>
		</a>
	</li>

	<ul class="logout">
		<li>
			<a href="http://startific.com">
            	<i class="fa fa-lightbulb-o fa-lg"></i>
                <span class="nav-text">BLOG</span>
			</a>
		</li>  
	</ul>-->
	<div class="container progres_custom">
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="progress blue">
                <span class="progress-left">
                    <span class="progress-bar"></span>
                </span>
                <span class="progress-right">
                    <span class="progress-bar"></span>
                </span>
                <div class="progress-value">90%</div>
            </div>
        </div>
    </div>
</div>

 	</div>
</nav> 



  


</body>
</html>


			
 

books/templates/books/dashboard.html
{% extends "books/base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}
	<div class="container">
		<h1>Ovo je DASHBOARD!</h1>
		<div class="row">
			<div class="col-md-3" style="text-align: center">
				<a href="{% url 'dashboard:enter_new_book' %}">
					<img src='/media/cover_image/add_new.png' width='100%' height='350px' />
				</a>
			</div>
			{% for book in books %}
				<div class="col-md-3" style="text-align: center">
					<a href="{% url 'dashboard:details_books' book.id %}">
						<img src='/media/{{ book.cover }}' width='100%' height='350px' />
					</a>
					<h3>{{ book.title }}</h3>
					<p>{{ book.subtitle }}</p>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

books/templates/books/details_books.html
{% extends "books/base.html" %}

{% block title %}
	Book - {{ book.title }}
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-3">
			</div>
			<div class="col-md-6" style="text-align: center">
				<img src='/media/{{ book.cover }}' width='70%' height='450px' />
				<h1>{{ book.title }}</h1>
				<p>{{ book.subtitle }}</p>
				<h5>Description:</h5>
				<p>{{ book.description }}</p>
				<h5>Authors:</h5>
				{% for x in book.author.all %}
					<p>{{ x }};</p>
				{% endfor %}
				<h5>Comparible:</h5>
				<a href="{{ book.comparible }}"><p>{{ book.comparible }}</p></a>
				<h5>Co authors:</h5>
				{% for x in book.co_author_name.all %}
					<p>{{ x }}</p>
				{% endfor %}
				<h5>Co authors emails:</h5>
				{% for x in book.co_author_email.all %}
					<p>{{ x }}</p>
				{% endfor %}
				<h5>Co authors instructions:</h5>
				<p>{{ book.co_author_instructions }}</p>
				<a href="../" class="btn btn-outline-danger page-scroll btn-lg page-scroll">Back</a>
				<a href="edit/" class="btn btn-outline-primary btn-lg page-scroll">Edit</a>
			</div>
			<div class="col-md-3">
			</div>
		</div>
	</div>
{% endblock %}

books/templates/books/displaying_emails_using_ajax.html
{% for mail in mails %}
	<option value="{{mail.pk}}">{{ mail.email }}</option>
{% endfor %}

books/templates/books/edit_books.html
{% extends "books/base.html" %}

{% block other_css %}
	{{ form.media.css }}
{% endblock %}

{% block title %}
	Book - {{ book.title }}
{% endblock %}

{% block content %}
	<div class="container">
		<form method="post" novalidate enctype="multipart/form-data">
			{% csrf_token %}
			{% include 'includes/bs4_edit_form.html' with form=form %}
			<div class="row custom_buttons">
				<a href="../" class="btn btn-outline-danger page-scroll btn-lg col-md-3">Cancel</a>
				<button type="submit" class="btn btn-outline-primary btn-lg col-md-3 offset-md-5">Save</button>
			</div>
		</form>
	</div>
{% endblock %}

{% block other_js %}
	{{ form.media.js }}
{% endblock %}

books/templates/books/enter_new_book.html
{% extends "books/base.html" %}

{% block other_css %}
	{{ form.media.css }}
{% endblock %}

{% block title %}
	New Book
{% endblock %}

{% block content %}
	<div class="container">
		<form id="enterNewBookForm" data-emails-url="{% url 'dashboard:ajax_load_emails' %}" method="post" novalidate enctype="multipart/form-data">
			{% csrf_token %}
			{% include 'includes/bs4_form.html' with form=form %}
			<div class="row custom_buttons">
				<a href="./" class="btn btn-outline-danger page-scroll btn-lg col-md-3">Back</a>
				<button type="submit" class="btn btn-outline-secondary btn-lg col-md-3 offset-md-2" name="save_and_add_another">Save and add another</button>
				<button type="submit" class="btn btn-outline-primary btn-lg col-md-3">Save</button>
			</div>
		</form>
	</div>
{% endblock %}

{% block other_js %}
	{{ form.media.js }}
{% endblock %}

books/templates/books/index.html
{% extends "books/base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}
	<div class="container">
		<h1>Ovo je HOME!</h1>
	</div>
{% endblock %}

books/templates/includes/bs4_edit_form.html
{% load widget_tweaks %}
{% for hidden_field in form.hidden_fields %}
	{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{ error }}
		{% endfor %}
	</div>
{% endif %}
<div class="row">
	{% for field in form.visible_fields %}
		{% if forloop.counter == 3 or forloop.counter == 7 %}
			<div class="form-group col-sm-12">
				{{ field.label_tag }}

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
					  	{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% elif forloop.counter == 4 or forloop.counter == 5 or forloop.counter == 6%}
			<div class="form-group col-sm-4">
				{{ field.label_tag }}

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% elif forloop.counter == 9 %}
			<div class="form-group col-sm-6">
				{{ field.label_tag }}<br>
				
				<img src="/media/{{ book.cover }}" width="100px" height="100px">

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% else %}
			<div class="form-group col-sm-6">
				{{ field.label_tag }}

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% endif %}
	{% endfor %}
</div>

books/templates/includes/bs4_form.html
{% load widget_tweaks %}
{% for hidden_field in form.hidden_fields %}
	{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{ error }}
		{% endfor %}
	</div>
{% endif %}
<div class="row">
	{% for field in form.visible_fields %}
		{% if forloop.counter == 3 or forloop.counter == 7 %}
			<div class="form-group col-sm-12">
				{{ field.label_tag }}

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
					  	{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% elif forloop.counter == 4 or forloop.counter == 5 %}
			<div class="form-group col-sm-4">
				{{ field.label_tag }}

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% elif forloop.counter == 6 %}
			<div class="col-sm-4 form-group">
					{{ field.label_tag }}

					{% if form.is_bound %}
						{% if field.errors %}
							{% render_field field class="form-control is-invalid" %}
							{% for error in field.errors %}
								<div class="invalid-feedback">
									{{ error }}
								</div>
							{% endfor %}
						{% else %}
							{% render_field field class="form-control is-valid" %}
						{% endif %}
					{% else %}
						{% render_field field class="form-control" %}
					{% endif %}

					{% if field.help_text %}
						<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
			</div>
		{% else %}
			<div class="form-group col-sm-6">
				{{ field.label_tag }}

				{% if form.is_bound %}
					{% if field.errors %}
						{% render_field field class="form-control is-invalid" %}
						{% for error in field.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}

				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
			</div>
		{% endif %}
	{% endfor %}
</div>
{% block other_js %}
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
	<script>
		$(document).ready(function(){
			$("#id_co_author_name").change(function () {
		      var url = $("#enterNewBookForm").attr("data-emails-url");  // get the url of the `load_cities` view
		      var authorId = $(this).val();  // get the selected author ID from the HTML input
		      console.log(authorId)

		      $.ajax({                       // initialize an AJAX request
		        url: url,                    // set the url of the request)
		        data: {
		          'authorId[]': authorId       // add the country id to the GET parameters
		        },
		        success: function (data) {   // `data` is the return of the `load_cities` view function
		          $("#id_co_author_email").html(data);  // replace the contents of the city input with the data that came from the server
		        }
		      });

		    });
		});
	</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>